In [5]:
import numpy as np
import pandas as pd

In [43]:
L = pd.DataFrame([
    [0, 0, 1, 0],
    [1, 0, 0, 0],
    [1, 1, 0, 1],
    [0, 0, 0, 0]
])
d = 0.85

E = pd.DataFrame(np.ones([4, 4]) / 4)
D = np.diag(np.sum(L, axis=0))
D_inv = np.linalg.inv(D)
A = d * L @ D_inv  + (1 - d) * E
p0 = np.ones(4)

In [53]:
A

        0       1       2       3
0  0.0375  0.0375  0.8875  0.0375
1  0.4625  0.0375  0.0375  0.0375
2  0.4625  0.8875  0.0375  0.8875
3  0.0375  0.0375  0.0375  0.0375

In [52]:
p = p0.copy()
for i in range(100):
    p = A @ p
    p = p / p.sum()
p

0    0.372527
1    0.195824
2    0.394149
3    0.037500
dtype: float64

In [47]:
A

        0       1       2       3
0  0.0375  0.0375  0.8875  0.0375
1  0.4625  0.0375  0.0375  0.0375
2  0.4625  0.8875  0.0375  0.8875
3  0.0375  0.0375  0.0375  0.0375

In [49]:
A.sum(axis=1)

0    1.000
1    0.575
2    2.275
3    0.150
dtype: float64